name: "Send Deployment Notification"
description: "A GitHub Action to send deployment notifications via email using Microsoft Graph API and Azure AD."
author: "marcus-hooper"
runs:
  using: "composite"
  steps:
    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}\requirements.txt
      shell: powershell

    # Run the notification script
    - name: Send notification
      run: |
        python ${{ github.action_path }}\send_deployment_notification.py
      env:
        GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        GITHUB_ENVIRONMENT: ${{ env.GITHUB_ENVIRONMENT }}
        COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
        NOTIFICATION_TO: ${{ env.NOTIFICATION_TO }}
        NOTIFICATION_FROM: ${{ env.NOTIFICATION_FROM }}
        AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ env.AZURE_CLIENT_SECRET }}
      shell: powershell
