name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type:bug", "priority:medium"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

        **Before submitting**, please review the [README](https://github.com/marcus-hooper/deployment-notification-o365#readme) for usage guidance.

        **Tip**: Enable debug logging by adding `ACTIONS_STEP_DEBUG: true` to your repository secrets or workflow env. This provides more detailed output in the logs.

  - type: textarea
    id: description
    attributes:
      label: Bug Summary
      description: A brief, one or two sentence summary of the issue
      placeholder: "e.g., Email fails to send when NOTIFICATION_TO contains multiple addresses"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure workflow with...
        2. Trigger deployment...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: workflow-configuration
    attributes:
      label: Workflow Configuration
      description: Paste your workflow YAML here (redact secrets).
      render: yaml
      placeholder: |
        - name: Send deployment notification
          uses: marcus-hooper/deployment-notification-o365@v1
          env:
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            NOTIFICATION_TO: team@example.com
            NOTIFICATION_FROM: deployments@example.com

  - type: dropdown
    id: runner-os
    attributes:
      label: Runner OS
      description: Which runner are you using?
      options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-slim
        - ubuntu-24.04-slim
        - ubuntu-24.04-arm
        - ubuntu-22.04-arm
        - windows-latest
        - windows-2025
        - windows-2022
        - windows-11-arm
        - macos-latest
        - macos-15
        - macos-15-intel
        - macos-14
        - macos-13
        - Self-hosted (specify in additional context)
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: action-version
    attributes:
      label: Action Version
      description: Which version of the action are you using?
      placeholder: "v1, main, or specific SHA"
    validations:
      required: true

  - type: dropdown
    id: azure-ad
    attributes:
      label: Azure AD Mail.Send Permission Configured?
      options:
        - "Yes"
        - "No"
        - "Unsure"
    validations:
      required: false

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: The Python version shown in the workflow logs
      placeholder: "3.13"
    validations:
      required: false

  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: The exact error message (if any), including stack traces
      render: shell
      placeholder: |
        CredentialUnavailableError: ClientSecretCredential authentication failed
        File "send_deployment_notification.py", line 45, in initialize_graph_client

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs here (redact sensitive info).
      placeholder: Expand the "Send deployment notification" step and copy relevant output
      render: shell
    validations:
      required: true

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have [searched existing issues](https://github.com/marcus-hooper/deployment-notification-o365/issues?q=is%3Aissue) for duplicates
          required: true
        - label: Azure AD app has Mail.Send permission
          required: true
        - label: Sender mailbox exists in Microsoft 365

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information.
